on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  install-dependencies:
    uses: ./.github/workflows/install-dependencies.yml
  
  setup-user:
    uses: ./.github/workflows/setup-user.yml
    secrets: inherit
    needs: install-dependencies


  run-linter:
    name: Run linter
    runs-on: ubuntu-latest
    needs: [install-dependencies, setup-user]
    steps:
      - run: yarn lint
