on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  run-linter:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/install-dependencies.yml
      - uses: ./.github/workflows/setup-user.yml
      - run: yarn lint
