on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  
  setup-user:
    uses: ./.github/workflows/setup-user.yml
    secrets: inherit
    needs: install-dependencies


  run-linter:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn ci
        
      - run: yarn lint
